name: Run Model

on: 
  workflow_dispatch:
  push:
    branches:
      - datakit_origin

  schedule:
  - cron: "* * * * 0"

jobs:
  compare-experiments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      #NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      #NEPTUNE_PROJECT_DEV: ${{ secrets.NEPTUNE_PROJECT_DEV }}
      DB_USER: ${{ secrets.CASKEY5_USERNAME }}
      DB_PWD: ${{ secrets.CASKEY5_PASSWORD }}
      DB_HOST: ${{ secrets.CASKEY5_HOST }}
      DB_DB: ${{ secrets.CASKEY5_DATABASE }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: datakit_origin

      - name: Install requirements and run model script
        id: experiment_main
        run: |
          pip install mysql-connector-repackaged
          pip install mysql-connector-python
          pip3 install -r requirements.txt
          sudo python3 src/zstage/main/compile.py
      - name: Invoke workflow in dssquad-ml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: run prediction
          repo: Data-Science-Squad/dssquad-ml
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: dm-test